//Code generated by generator, DO NOT EDIT.
package repository

import (
	"context"
	"fmt"

	sq "github.com/Masterminds/squirrel"
)

// CreateUser inserts a new User into the database.
func (r *repository) CreateUser(ctx context.Context, user *User) error {
	query, args := sq.Insert(TableUser).
		Columns(ColumnUserID, ColumnUserName, ColumnUserEmail).
		Values(user.ID, user.Name, user.Email).PlaceholderFormat(sq.Dollar).MustSql()

	if _, err := r.db.Exec(ctx, query, args...); err != nil {
		return fmt.Errorf("failed to exec create query %s with args %v", query, args)
	}
	return nil
}
