//Code generated by generator, DO NOT EDIT.
package repository



import (
	"context"
	"fmt"
	"database/sql"
	sq "github.com/Masterminds/squirrel"
)



// CreateUser inserts a new User into the database.
func (r *CommandRepository) Create(ctx context.Context,  user *User) error {
	model := Converter(*user)
	query, args := sq.Insert(TableUser).
		Columns(ColumnUserID, ColumnUserName, ColumnUserEmail, ColumnUserBalance).
		Values(model.Values()...).PlaceholderFormat(sq.Question).MustSql()

	if _, err := r.db.Exec(ctx, query, args...); err != nil {
		return fmt.Errorf("failed to exec create query %s with args %v error = %w", query, args, err)
	}
	return nil
}



func CreateSQLTx(ctx context.Context, run *sql.Tx, user *User) error {
	model := Converter(*user)
	query, args := sq.Insert(TableUser).
		Columns(ColumnUserID, ColumnUserName, ColumnUserEmail, ColumnUserBalance).
		Values(model.Values()...).PlaceholderFormat(sq.Question).MustSql()

	if _, err := run.ExecContext(ctx, query, args...); err != nil {
		return fmt.Errorf("failed to exec create query %s with args %v error = %w", query, args, err)
	}
	return nil
}