//Code generated by generator, DO NOT EDIT.
package repository

import (
	"context"
	"fmt"

	sq "github.com/Masterminds/squirrel"
	"github.com/google/uuid"
)

// DeleteUser deletes a User by ID.
func (r *repository) DeleteUser(ctx context.Context, id uuid.UUID) error {
	query, args := sq.Delete(TableUser).
		Where(sq.Eq{ColumnUserID: id}).PlaceholderFormat(sq.Dollar).MustSql()

	if _, err := r.db.Exec(ctx, query, args...); err != nil {
		return fmt.Errorf("failed to exec delete query %s with args %v error = %w", query, args, err)
	}
	return nil
}


// DeleteManyUser retrieves a User by ID.
func (r *repository) DeleteManyUsers(ctx context.Context, f UserFilter) ([]User, error) {
	b := sq.Delete(TableUser).PlaceholderFormat(sq.Dollar)

	b = ApplyWhere(b, f)

    query, args := 	b.MustSql()

    var users []User

	rows, err := r.db.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("error querying database: %w", err)
	}
	defer rows.Close()


	var user User
	for rows.Next() {
		err := rows.Scan(&user)
		if err != nil {
			return nil, fmt.Errorf("error scanning row: %w", err)
		}
		users = append(users, user)
	}

	if rows.Err() != nil {
		return nil, fmt.Errorf("error iterating rows: %w", rows.Err())
	}


	return users, err
}
