//Code generated by generator, DO NOT EDIT.
package repository

const (
	TableUser = "users"
	ColumnUserID = "id"
	ColumnUserName = "name"
	ColumnUserEmail = "email"
	ColumnUserBalance = "balance"
)


func (m User) Values() []any {
	return []any {
			m.ID,
			m.Name,
			m.Email,
			m.Balance,
	}
}

