//Code generated by generator, DO NOT EDIT.

/*
Example SQL for PostgreSQL table creation:

CREATE TABLE IF NOT EXISTS nav_history (
    id INTEGER NOT NULL PRIMARY KEY,
    robot_id INTEGER NOT NULL,
    nav NUMERIC NOT NULL,
    created_at TEXT NOT NULL
);

*/
package main

import (
	"context"

	"github.com/AugustineAurelius/eos/pkg/generics"
	sq "github.com/Masterminds/squirrel"
)

// builderParams represents optional query parameters.
type BuilderParams struct {
	OrderBy   *string // Column and direction for sorting (e.g., "id ASC")
	SearchCol *string // Column to search in (e.g., "name")
	SearchTerm *string // Term to search for (e.g., "alice")
	Offset    *int    // Initial offset for pagination
	Limit     *int    // Number of rows to fetch per batch
	MaxRows    *int
}

type Cursor struct {
	pool      querier 
	builder   sq.SelectBuilder
	rows      []NavHistory
	index     int
	offset    int
	limit     int
	params    BuilderParams
	ctx       context.Context
	totalRows int 
	closed    bool 
}

type Query interface {
	Get(ctx context.Context, opts ...FilterOpt) (*NavHistory, error)
	GetMany(ctx context.Context, opts ...FilterOpt) (generics.SliceOps[NavHistory], error)
	Has(ctx context.Context, opts ...FilterOpt) (bool, error)
	GetIterator(ctx context.Context, opts ...FilterOpt) generics.IterWithErr[NavHistory]
	Count(ctx context.Context, opts ...FilterOpt) (int, error)
	NewCursor(ctx context.Context, params BuilderParams, opts ...FilterOpt) *Cursor
}

type Command interface {
	Query
	Create(ctx context.Context, model *NavHistory) error
	CreateMany(ctx context.Context, navhistorys []NavHistory) error
	Update(ctx context.Context, u Update, opts ...FilterOpt) error
	Upsert(ctx context.Context, model *NavHistory) error
	Save(ctx context.Context, model *NavHistory) error
	Delete(ctx context.Context, opts ...FilterOpt) error
}
