//Code generated by generator, DO NOT EDIT.
package main

const (
	TableNavHistory = "nav_history"
	ColumnNavHistoryID = "id"
	ColumnNavHistoryRobotID = "robot_id"
	ColumnNavHistoryNav = "nav"
	ColumnNavHistoryCreatedAt = "created_at"
)
