version: "3.9"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres
            - zookeeper
            - kafka
            - kowl
        ports:
            - ${APP_PORT}:8080
        restart: unless-stopped
    kafka:
        depends_on:
            - zookeeper
        environment:
            ALLOW_PLAINTEXT_LISTENER: "yes"
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
            KAFKA_BROKER_ID: 1
            KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
            KAFKA_LOG4J_LOGGERS: kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_RESTART_ATTEMPTS: "10"
            KAFKA_RESTART_DELAY: "5"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
            ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
        image: bitnami/kafka:latest
        ports:
            - 9092:9092
        restart: on-failure
    kowl:
        depends_on:
            - kafka
        entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
        image: quay.io/cloudhut/kowl:v1.4.0
        ports:
            - 8080:8080
        restart: on-failure
        volumes:
            - ./kowl_config:/etc/kowl/
    postgres:
        command: |
            postgres -c max_connections=1000
                     -c shared_buffers=256MB
                     -c effective_cache_size=768MB
                     -c maintenance_work_mem=64MB
                     -c checkpoint_completion_target=0.7
                     -c wal_buffers=16MB
                     -c default_statistics_target=100
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_DB: ${POSTGRES_DATABASE}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        image: postgres:latest
        ports:
            - ${POSTGRES_PORT}:5432
    zookeeper:
        environment:
            ALLOW_ANONYMOUS_LOGIN: "yes"
            ZOO_MY_ID: 1
            ZOO_PORT: 2181
            ZOO_SERVERS: server.1=zookeeper:2888:3888
        image: bitnami/zookeeper:latest
        ports:
            - 2181:2181
        restart: on-failure
