//Code generated by generator, DO NOT EDIT.
package common

import (
	"context"
	"database/sql"
	"errors"
	"time"

	"github.com/ClickHouse/clickhouse-go/v2"
	"go.uber.org/zap"
	
	"go.opentelemetry.io/otel/metric"
	
	
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
    
)

type ClickhouseConnectionProvider struct {
	Host      string
	Port      int
	Databasse string
	User      string
	Password  string
}

type ClickHouseQuerier struct {
	client *sql.DB
	
	logger logger
	
	
	telemetry tracer
	
    
	queryCount      int64Counter
	execCount       int64Counter
	queryRowCounter int64Counter
	
}

func NewClickhouse(cp ClickhouseConnectionProvider,
	
	logger logger,
	
	
	telemetry tracer, 
	
	
	metrics metricProvider,
	
) (ClickHouseQuerier, error) {
	conn := clickhouse.OpenDB(&clickhouse.Options{
		Addr: []string{cp.Host},
		Auth: clickhouse.Auth{
			Database: cp.Databasse,
			Username: cp.User,
			Password: cp.Password,
		},
		Settings: clickhouse.Settings{
			"max_execution_time": 60,
		},
		DialTimeout: time.Second * 30,
		Compression: &clickhouse.Compression{
			Method: clickhouse.CompressionLZ4,
		},
		Debug:                true,
		BlockBufferSize:      10,
		MaxCompressionBuffer: 10240,
	})
	conn.SetMaxIdleConns(5)
	conn.SetMaxOpenConns(10)
	conn.SetConnMaxLifetime(time.Hour)

	
	queryCount, err := metrics.Int64Counter("queryCount",metric.WithDescription("Clickhouse"))
	if err != nil {
		return ClickHouseQuerier{}, err
	}
	execCount, err := metrics.Int64Counter("execCount",metric.WithDescription("Clickhouse"))
	if err != nil {
		return ClickHouseQuerier{}, err
	}
	queryRowCounter, err := metrics.Int64Counter("queryRowCounter",metric.WithDescription("Clickhouse"))
	if err != nil {
		return ClickHouseQuerier{}, err 
	}
	
	return ClickHouseQuerier{client: conn,
		
		logger:          logger,
		
		
		telemetry:       telemetry,
		
		
		queryCount:      queryCount,
		execCount:       execCount,
		queryRowCounter: queryRowCounter,
		
}, nil
}


func (db *ClickHouseQuerier) QueryRow(ctx context.Context, query string, args ...any) row {
	
	ctx, span := db.telemetry.Start(ctx, "QueryRow",trace.WithAttributes(attribute.String("query", query), attribute.String("db_type", "Clickhouse")))
	defer span.End()
    
	
	start := time.Now()
	db.logger.Info("Executing QueryRow", zap.String("query", query))
	
	row := db.client.QueryRowContext(ctx, query, args...)
	
	duration := time.Since(start).Seconds()
	db.logger.Info("QueryRow succeeded", zap.Float64("duration", duration))
	
	
	db.queryRowCounter.Add(ctx, 1)
	
	return &ClickHouseRow{row}
}

func (db *ClickHouseQuerier) Query(ctx context.Context, query string, args ...any) (rows, error) {
	
	ctx, span := db.telemetry.Start(ctx, "Query",trace.WithAttributes(attribute.String("query", query), attribute.String("db_type", "Clickhouse")))
	defer span.End()
    
	
    start := time.Now()
    db.logger.Info("Executing Query", zap.String("query", query))
	
	rows, err := db.client.QueryContext(ctx, query, args...)
	if err != nil {
		
		span.SetStatus(codes.Error, err.Error())
		span.RecordError(err)
        
		
        db.logger.Error("Query failed", zap.Error(err))
		
		return nil, err
	}
	
	duration := time.Since(start).Seconds()
    db.logger.Info("Query succeeded", zap.Float64("duration", duration))
	
	
	db.queryCount.Add(ctx, 1)
    
	return &ClickHouseRows{rows}, nil
}

func (db *ClickHouseQuerier) Exec(ctx context.Context, query string, args ...any) (result, error) {
	
    ctx, span := db.telemetry.Start(ctx, "Exec",trace.WithAttributes(attribute.String("query", query), attribute.String("db_type", "Clickhouse")))
    defer span.End()
    
	
	start := time.Now()
    db.logger.Info("Executing Exec", zap.String("query", query))
	
	res, err := db.client.ExecContext(ctx, query, args...)
	if err != nil {
		
		span.SetStatus(codes.Error, err.Error())
		span.RecordError(err)
        
		
        db.logger.Error("Exec failed", zap.Error(err))
		
		return nil, err
	}
	
    duration := time.Since(start).Seconds()
    db.logger.Info("Exec succeeded", zap.Float64("duration", duration))
	
	
	db.execCount.Add(ctx, 1)
    
	return &ClickHouseResult{res}, nil
}

type ClickHouseRows struct {
	rows
}

func (r *ClickHouseRows) Err() error {
	return r.rows.Err()
}

func (r *ClickHouseRows) Next() bool {
	return r.rows.Next()
}

func (r *ClickHouseRows) Close() error {
	return r.rows.Close()
}

func (r *ClickHouseRows) Scan(dest ...any) error {
	return r.rows.Scan(dest...)
}

type ClickHouseRow struct {
	row
}

func (r *ClickHouseRow) Scan(dest ...any) error {
	return r.row.Scan(dest...)
}

type ClickHouseResult struct {
	result
}

func (r *ClickHouseResult) RowsAffected() (int64, error) {
	return r.result.RowsAffected()
}

type ClickHouseBegginer struct {
	*ClickHouseQuerier
}

func (b *ClickHouseBegginer) Begin(ctx context.Context) (Tx, error) {
	return &ClickHouseTx{}, errors.New("not supported")
}

type ClickHouseTx struct {
	*ClickHouseQuerier
}

func (t *ClickHouseTx) Commit(ctx context.Context) error {
	return errors.New("not supported")

}

func (t *ClickHouseTx) Rollback(ctx context.Context) error {
	return errors.New("not supported")
}

