//Code generated by generator, DO NOT EDIT.
package common

import (
    "database/sql"

    _ "github.com/ClickHouse/clickhouse-go/v2" 
)


func NewClickhouse(cfg URIer) (*sql.DB, error) {
	db, err := sql.Open("clickhouse", cfg.URI())
	if err != nil {
		return nil, err
	}

	return db, err
}
