// Code generated by g
package common

import (
	"context"
)

type ConnectionProvider interface {
	GetConnectionURL() string
}

type Querier interface {
	Query(ctx context.Context, query string, args ...any) (rows, error)
	QueryRow(ctx context.Context, query string, args ...any) row
	Exec(ctx context.Context, query string, args ...any) (result, error)
}

type Database interface {
	Querier
	Begin(ctx context.Context) (Tx, error)
}

type rows interface {
	Err() error
	Close() error
	Scan(dest ...any) error
	Next() bool
}

type row interface {
	Scan(dest ...any) error
}

type Tx interface {
	Querier
	Commit(ctx context.Context) error
	Rollback(ctx context.Context) error
}

type result interface {
	RowsAffected() (int64, error)
}
