// Code generated by generator, DO NOT EDIT.
package common

import (
	"database/sql"

	_ "github.com/jackc/pgx/v5/stdlib"
)

func NewPostgres(cfg URIer) (*sql.DB, error) {
	db, err := sql.Open("pgx", cfg.URI())
	if err != nil {
		return nil, err
	}

	return db, err
}
