# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Fix Docker permissions
      run: sudo chmod 666 /var/run/docker.sock
    
    - name: Run compose up for test Docker
      run: docker-compose -f ./example/repository/docker-compose.yaml up -d --build

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'
        
    - name: Install dependencies
      run: go get .

    - name: Build
      run: go build -v ./...

    - name: Test
      env:
        DOCKER_HOST: unix:///var/run/docker.sock
      run: go test -v ./...

    - name: Stop Docker Compose services
      run: docker-compose -f ./example/repository/docker-compose.yaml down
      if: always()
