# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Fix Docker permissions
      run: sudo chmod 666 /var/run/docker.sock
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Run compose up for test Docker
      run: |
        export PATH=/usr/local/bin:$PATH
          if command -v docker compose &> /dev/null
          then
              echo "Using docker compose"
              docker compose -f ./teste_env/docker-compose.yaml up -d --build
          else
              echo "Installing docker-compose"
              curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              chmod +x /usr/local/bin/docker-compose
              docker-compose -f ./teste_env/docker-compose.yaml up -d --build
          fi
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'
        
    - name: Install dependencies
      run: go get .

    - name: Build
      run: go build -v ./...

    - name: Test
      env:
        DOCKER_HOST: unix:///var/run/docker.sock
      run: go test -v ./...

    - name: Stop Docker Compose services
      run: |
        export PATH=/usr/local/bin:$PATH
          if command -v docker compose &> /dev/null
          then
              echo "Using docker compose"
              docker compose -f ./teste_env/docker-compose.yaml down
          else
              echo "Installing docker-compose"
              curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              chmod +x /usr/local/bin/docker-compose
              docker-compose -f ./teste_env/docker-compose.yaml down
          fi
      if: always()
